groups:
  - name: Terralemon
    schedule: '*/60 * * * *'
    urls:
      - https://terralemon.nl
    options:
      scrollToBottom: false
      waitForSelector: main
      crawl: true
      crawl_depth: 1
      userAgent: TerraCache/1.0.0
