/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StatusRouteImport } from './routes/status'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HistoryRunIdRouteImport } from './routes/history_.$runId'
import { Route as GroupsGroupNameRouteImport } from './routes/groups_.$groupName'

const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRunIdRoute = HistoryRunIdRouteImport.update({
  id: '/history_/$runId',
  path: '/history/$runId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsGroupNameRoute = GroupsGroupNameRouteImport.update({
  id: '/groups_/$groupName',
  path: '/groups/$groupName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/groups': typeof GroupsRoute
  '/history': typeof HistoryRoute
  '/status': typeof StatusRoute
  '/groups/$groupName': typeof GroupsGroupNameRoute
  '/history/$runId': typeof HistoryRunIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/groups': typeof GroupsRoute
  '/history': typeof HistoryRoute
  '/status': typeof StatusRoute
  '/groups/$groupName': typeof GroupsGroupNameRoute
  '/history/$runId': typeof HistoryRunIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/groups': typeof GroupsRoute
  '/history': typeof HistoryRoute
  '/status': typeof StatusRoute
  '/groups_/$groupName': typeof GroupsGroupNameRoute
  '/history_/$runId': typeof HistoryRunIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/groups'
    | '/history'
    | '/status'
    | '/groups/$groupName'
    | '/history/$runId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/groups'
    | '/history'
    | '/status'
    | '/groups/$groupName'
    | '/history/$runId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/groups'
    | '/history'
    | '/status'
    | '/groups_/$groupName'
    | '/history_/$runId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  GroupsRoute: typeof GroupsRoute
  HistoryRoute: typeof HistoryRoute
  StatusRoute: typeof StatusRoute
  GroupsGroupNameRoute: typeof GroupsGroupNameRoute
  HistoryRunIdRoute: typeof HistoryRunIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history_/$runId': {
      id: '/history_/$runId'
      path: '/history/$runId'
      fullPath: '/history/$runId'
      preLoaderRoute: typeof HistoryRunIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups_/$groupName': {
      id: '/groups_/$groupName'
      path: '/groups/$groupName'
      fullPath: '/groups/$groupName'
      preLoaderRoute: typeof GroupsGroupNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  GroupsRoute: GroupsRoute,
  HistoryRoute: HistoryRoute,
  StatusRoute: StatusRoute,
  GroupsGroupNameRoute: GroupsGroupNameRoute,
  HistoryRunIdRoute: HistoryRunIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
